=== mscg82/opencms-backoffice/app-starter/app-starter-common/src/main/resources/com/mscg/appstarter/beans/jaxb/app-starter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:complexType name="ServerMessage">
        <xs:sequence>
            <xs:element name="exceptionClass" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="messageBody" type="xs:string" minOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Login">
        <xs:sequence>
            <xs:element name="username"   type="xs:string" minOccurs="0" />
            <xs:element name="nonce"      type="xs:string" minOccurs="0" />
            <xs:element name="identifier" type="xs:string" minOccurs="0" />
            <xs:element name="sessionID"  type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ApplicationInfo">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" />
        <xs:attribute name="running" type="xs:boolean" />
    </xs:complexType>
    
    <xs:complexType name="ApplicationsList">
        <xs:sequence>
            <xs:element name="application" type="ApplicationInfo" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Response">
        <xs:sequence>
            <xs:element name="message" type="ServerMessage" minOccurs="0" />
            <xs:element name="login" type="Login" minOccurs="0" />
            <xs:element name="applications" type="ApplicationsList" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="status" type="xs:int" />
    </xs:complexType>
    
    <xs:complexType name="Request">
        <xs:sequence>
            <xs:element name="login" type="Login" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="wrapper">
	    <xs:complexType>
	        <xs:sequence>
	            <xs:element name="response" type="Response" minOccurs="0" />
	            <xs:element name="request"  type="Request" minOccurs="0"/>
	        </xs:sequence>
	    </xs:complexType>
    </xs:element>
    
</xs:schema>

=== mscg82/opencms-backoffice/app-starter/app-starter-common/src/main/resources/com/mscg/appstarter/beans/jaxb/app-starter.xml
<?xml version="1.0" encoding="UTF-8"?>
<wrapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="app-starter.xsd">
  <response status="0">
    <message>
      <exceptionClass>exceptionClass</exceptionClass>
      <messageBody>messageBody</messageBody>
    </message>
    <login>
      <username>username</username>
      <nonce>nonce</nonce>
      <identifier>identifier</identifier>
      <sessionID>sessionID</sessionID>
    </login>
  </response>
  <request>
    <login>
      <username>username</username>
      <nonce>nonce</nonce>
      <identifier>identifier</identifier>
      <sessionID>sessionID</sessionID>
    </login>
  </request>
</wrapper>
